VLTIF: src/feature/FeaturePointUtilities.h File Reference
FeaturePointUtilities.h File Reference
#include <cv.h>
#include <cvaux.h>
#include <highgui.h>
#include <vector>
#include "../core/PointTracker.h"
#include "../core/Enumerations.h"
Functions
size_t compute_area (size_t i, size_t j, Size bbox)
void compute_point_density (Mat &imageOut, vector< Tuple > &keypoints, Size imgSize, Size bbox)
Function Documentation
size_t compute_area (size_t i, size_t j, Size bbox)
Definition at line 110 of file FeaturePointUtilities.h.
{
    size_t area = 0;
    for( size_t i=0; i<bbox.width; i++){
        for( size_t j=0; j<bbox.height; j++){
            if( i >= 0 && j >= 0 )
                area += 1;
        }
    }
    return area;
}
void compute_point_density (Mat & imageOut, vector< Tuple > & keypoints, Size imgSize, Size bbox)
Definition at line 29 of file FeaturePointUtilities.h.
References COLOR_GREEN, Enumerations::color_interp(), COLOR_RED, and Enumerations::Scalar2Vec().
Referenced by main().
{
    Enumerations REF;
    Mat integralImage = Mat(Size(imageOut.cols, imageOut.rows), CV_32FC1);
    Mat integralImage2= Mat(Size(imageOut.cols, imageOut.rows), CV_32FC1);
    Mat densityImage  = Mat(Size(imageOut.cols, imageOut.rows), CV_32FC1);
    double area;
    int xmin, xmax, ymin, ymax;
    int count;
    Scalar val;
    int half = bbox.height/2;
    imageOut = Scalar(0,0,0,0);
    integralImage = Scalar(0,0,0,0);
    integralImage2 = Scalar(0,0,0,0);
    densityImage = Scalar(0,0,0,0);
    //iterate through points, incrementing the count
    for(size_t i=0; i<keypoints.size(); i++){
        if( keypoints[i].strength < 0.4 || keypoints[i].span < 5)
            integralImage.at<float>(keypoints[i].centroid) += .11;
        else if( keypoints[i].strength >= 0.4 )
            integralImage.at<float>(keypoints[i].centroid) -= .1;
    }
    //build the integral image
    for(int i=0; i<integralImage.cols; i++)
        for(int j=0; j<integralImage.rows; j++){
            xmin = max( i-1, 0);
            ymin = max( j-1, 0);
            if( i == 0 && j == 0 )
                integralImage2.at<float>(j,i) = integralImage.at<float>(j,i);
            else if( i == 0 )
                integralImage2.at<float>(j,i) = integralImage2.at<float>(j-1, i)
                                              + integralImage.at<float>(j,i);
            else if( j == 0 )
                integralImage2.at<float>(j,i) = integralImage2.at<float>(j, i-1)
                                              + integralImage.at<float>(j,i);
            else
                integralImage2.at<float>(j,i) = integralImage.at<float>(j,i) +
                                                integralImage2.at<float>(ymin, i) +
                                                integralImage2.at<float>(j, xmin) -
                                                integralImage2.at<float>(ymin,xmin);
        }
    //compute the density map
    for(int i=1; i<integralImage.cols; i++)
        for(int j=0; j<integralImage.rows; j++){
            xmin = max(i-half-1, 0);
            ymin = max(j-half-1, 0);
            xmax = min(i+half  , integralImage.cols-1);
            ymax = min(j+half  , integralImage.rows-1);
            //iterate over map
            densityImage.at<float>(j,i) = integralImage2.at<float>( ymax, xmax)
                                        - integralImage2.at<float>( ymin, xmax)
                                        - integralImage2.at<float>( ymax, xmin)
                                        + integralImage2.at<float>( ymin, xmin);
            //densityImage.at<float>(j,i) /= (xmax-xmin-1)*(ymax-ymin-1);
        }
    for(int i=1; i<integralImage.cols; i++)
        for(int j=0; j<integralImage.rows; j++){
            if( densityImage.at<float>(j,i) < 0 )
                densityImage.at<float>(j,i) = 0;
            if( densityImage.at<float>(j,i) > 1)
                densityImage.at<float>(j,i) = 1;
        }
    normalize( densityImage, densityImage, 0, 1, CV_MINMAX);
    for(int i=1; i<integralImage.cols; i++)
        for(int j=0; j<integralImage.rows; j++){
            imageOut.at<Vec3b>(j,i) = REF.Scalar2Vec(REF.color_interp(COLOR_RED, COLOR_GREEN, densityImage.at<float>(j,i)));
        }
}