VLTIF: src/core/GeometryUtilities.h File Reference
GeometryUtilities.h File Reference
#include <cv.h>
#include <cvaux.h>
#include <highgui.h>
#include <iostream>
Functions
Rect expandRect (const Rect &bbox, size_t const &dist, Size const &imgSize)
bool pointsEqual (KeyPoint const &a, KeyPoint const &b)
double PointDistanceL1 (const Point &a, const Point &b)
double PointDistanceL2 (const Point &a, const Point &b)
double DescriptorDistanceL1 (const Mat &a, const Mat &b)
double DescriptorDistanceL2 (const Mat &a, const Mat &b)
Function Documentation
double DescriptorDistanceL1 (const Mat & a, const Mat & b)
Definition at line 31 of file GeometryUtilities.cpp.
{
    if( a.rows != 1 )
        throw string("Error: First Matrix must only have 1 row");
    if( b.rows != 1 )
        throw string("Error: Second Matrix must only have 1 row");
    if( a.cols != b.cols )
        throw string("Error: Matrices must have equal number of columns");
    if( a.type() == CV_32FC1 )
        cout << "CV_32FC1" << endl;
    if( a.type() == CV_64FC1 )
        cout << "CV_64FC1" << endl;
    double dist = 0;
    double va, vb;
    for( size_t i=0; i<a.cols; i++)
        for( size_t j=0; j<b.cols; j++){
            va = a.at<float>(0, i);
            vb = b.at<float>(0, j);
            dist += sqrt((va-vb)*(va-vb));
        }
    return dist;
}
double DescriptorDistanceL2 (const Mat & a, const Mat & b)
Definition at line 55 of file GeometryUtilities.cpp.
Referenced by PointTracker::build_background().
{
    if( a.rows != 1 )
        throw string("Error: First Matrix must only have 1 row");
    if( b.rows != 1 )
        throw string("Error: Second Matrix must only have 1 row");
    if( a.cols != b.cols )
        throw string("Error: Matrices must have equal number of columns");
    double dist = 0;
    double va, vb;
    for( size_t i=0; i<a.cols; i++){
            va = a.at<float>(0, i);
            vb = b.at<float>(0, i);
            //cout << va << ", " << vb << endl;
            //cin.get();
            dist += std::fabs(va-vb);
        }
    return dist;
}
Rect expandRect (const Rect & bbox, size_t const & dist, Size const & imgSize)
Definition at line 3 of file GeometryUtilities.cpp.
Referenced by SiftType::compute_frame().
{
    int minX = std::max( bbox.tl().x-dist, (size_t)0);
    int minY = std::max( bbox.tl().y-dist, (size_t)0);
    int maxX = bbox.br().x+(2*dist);
    int maxY = bbox.br().y+(2*dist);
    if( maxX >= imgSize.width ) maxX = imgSize.width-1;
    if( maxY >= imgSize.height) maxY = imgSize.height-1;
    return Rect(minX, minY, maxX-minX, maxY-minY);
}
double PointDistanceL1 (const Point & a, const Point & b)
Definition at line 23 of file GeometryUtilities.cpp.
Referenced by PointTracker::build_background().
{
    return fabs((a.x-b.x) + (a.y-b.y));
}
double PointDistanceL2 (const Point & a, const Point & b)
Definition at line 27 of file GeometryUtilities.cpp.
Referenced by PointComp::operator()(), and PointTracker::point_match().
{
    return sqrt((a.x-b.x)*(a.x-b.x) + (a.y-b.y)*(a.y-b.y));
}
bool pointsEqual (KeyPoint const & a, KeyPoint const & b)
Definition at line 16 of file GeometryUtilities.cpp.
Referenced by SiftType::compute_frame().
{
    if( fabs(a.pt.x - b.pt.x) < 0.0001 )
        if( fabs(a.pt.y - b.pt.y) < 0.0001 )
            return true;
    return false;
}