VLTIF: src/ui/LaneDrawing.cpp File Reference
LaneDrawing.cpp File Reference
#include "LaneDrawing.h"
Functions
void lane_manager (Options &options)
vector< Lane > draw_lanes (const Mat &avg_frame)
vector< Lane > load_lanes (const string &filename, const string &vidname, bool &fail)
void save_lanes (const string &filename, vector< Lane > &lanes, const string &vidname)
Function Documentation
vector<Lane> draw_lanes (const Mat & avg_frame)
Make the user draw the lanes onto the median image
Parameters:
avg_frame,median frame
Returns:
list of lanes
Definition at line 81 of file LaneDrawing.cpp.
References Lane::addVertex(), Lane::changeLast(), Lane::clear(), COLOR_GREEN, Lane::draw(), mouse_flag, mouseFunc(), pX, pY, and Lane::size().
Referenced by lane_manager().
{
    cout << "-> " << avg_frame.cols << " x " << avg_frame.rows << endl;
    //start drawing loop
    Mat tframe;
    vector<Lane> existing_lanes;
    Lane tempLane;
    size_t prev_flag = mouse_flag;
    namedWindow("Lane Drawing Phase");
    setMouseCallback("Lane Drawing Phase", mouseFunc, 0);
    char key;
    cout << "aaa" << endl;
    while (true) {
        //clone original
        tframe = avg_frame.clone();
        cvtColor(avg_frame, tframe, CV_GRAY2BGR);
        //copy all exising polygons
        for (size_t i = 0; i < existing_lanes.size(); i++){
            existing_lanes[i].draw(tframe);
            rectangle( tframe, existing_lanes[i].bbox().tl(), existing_lanes[i].bbox().br(), Scalar(220, 220, 0), 1);
        }
        //copy current polygon under investigation
        if (mouse_flag == 1) {
            mouse_flag = 0;
            if (tempLane.size() > 0) {
                tempLane.changeLast(Point(pX, pY));
                tempLane.addVertex(Point(pX, pY));
            }
            if (tempLane.size() == 0) {
                tempLane.addVertex(Point(pX, pY));
                tempLane.addVertex(Point(pX, pY));
            }
        }
        tempLane.draw(tframe);
        if (tempLane.size() > 1)
            tempLane.changeLast(Point(pX, pY));
        imshow("Lane Drawing Phase", tframe);
        key = waitKey(30);
        if (key == 'q') {
            break;
        }
        if (key == 'x') {
            if (tempLane.size() >= 3) {
                existing_lanes.push_back(tempLane);
                existing_lanes.back().color = COLOR_GREEN;
                existing_lanes.back().finalize();
                tempLane.clear();
            }
        }
    }
    destroyWindow("Lane Drawing Phase");
    return existing_lanes;
}
void lane_manager (Options & options)
Compute the Median Frame
Definition at line 5 of file LaneDrawing.cpp.
References Options::avgFilename, draw_lanes(), Options::laneFilename, Options::lanes, load_lanes(), Options::loadAvgFrame, Options::loadLanes, median_frame(), save_lanes(), Options::saveAvgFrame, Options::saveLanes, Options::start_frame, and Options::video_filename.
Referenced by main().
{
    Mat avg_frame;
    //check to see if the lanes already exist, otherwise skip
    if( options.loadLanes == true ){
        if( bf::exists(bf::path(options.laneFilename))){
            bool fail;
            options.lanes = load_lanes(options.laneFilename, options.video_filename, fail);
            if( fail == false )
                return;
        }
    }
    /***********************/
    /*    AVERAGE LANE     */
    /***********************/
    //load the average frame
    bool frameExists = false;
    if( options.loadAvgFrame == true ){
        if(bf::exists(bf::path(options.avgFilename))){
            avg_frame = imread(options.avgFilename, 0);
            frameExists = true;
        }
        else{
            avg_frame = median_frame(options.video_filename, options.start_frame);
        }
    }
    else{
        avg_frame = median_frame(options.video_filename, options.start_frame);
    }
    //save the average frame
    if( options.saveAvgFrame == true && frameExists == false ){
        imwrite( options.avgFilename.c_str(), avg_frame);
    }
    /************************/
    /*     LANE DRAWING     */
    /************************/
    //load data
    bool laneExists = false;
    bool fail;
    if( options.loadLanes == true ){
        if( bf::exists(bf::path(options.laneFilename))){
            options.lanes = load_lanes(options.laneFilename, options.video_filename, fail);
            if( fail == true ){
                laneExists = false;
                options.lanes = draw_lanes( avg_frame );
            }
            else
                laneExists = true;
        }
        else{
            options.lanes = draw_lanes( avg_frame );
        }
    }
    else{
        options.lanes = draw_lanes( avg_frame );
    }
    //save data
    if( options.saveLanes == true && laneExists == false ){
        save_lanes( options.laneFilename, options.lanes, options.video_filename);
    }
}
vector<Lane> load_lanes (const string & filename, const string & vidname, bool & fail)
Definition at line 148 of file LaneDrawing.cpp.
References Lane::addVertex(), and Lane::clear().
Referenced by lane_manager().
{
    vector<Lane> lane_list;
    Lane tLane;
    Point pt;
    ifstream fin;
    fin.open(filename.c_str());
    //load video filename
    string fname;
    fin >> fname;
    if( vidname != fname ){
        fail = true;
        return lane_list;
    }
    else
        fail = false;
    //load size of lanes
    size_t lSize, npnts;
    fin >> lSize;
    for(size_t i=0; i<lSize; i++){
        //clear lane
        tLane.clear();
        //start loading points
        fin >> npnts;
        for(size_t j=0; j<npnts; j++){
            fin >> pt.x >> pt.y;
            tLane.addVertex(pt);
        }
        lane_list.push_back(tLane);
        lane_list.back().finalize();
    }
    fin.close();
    return lane_list;
}
void save_lanes (const string & filename, vector< Lane > & lanes, const string & vidname)
Definition at line 193 of file LaneDrawing.cpp.
Referenced by lane_manager().
{
    //open stream
    ofstream fout;
    fout.open(filename.c_str());
    fout << vidname << endl;
    fout << lanes.size() << endl;
    vector<Point> pnts;
    for( size_t i=0; i<lanes.size(); i++){
        pnts = lanes[i].getVertices();
        fout << pnts.size() << " ";
        for(size_t j=0; j<pnts.size(); j++)
            fout << pnts[j].x << " " << pnts[j].y << " ";
        fout << endl;
    }
    //close stream
    fout.close();
}