VLTIF: PointTracker Class Reference
PointTracker Class Reference
#include <PointTracker.h>
Public Member Functions
PointTracker ()
default constructor
vector< Tuple > update_points (vector< KeyPoint >const &list)
update the point positions
int point_match (Point2f const &pt)
Point Match.
void set_point_max_life (const int max_life)
Private Attributes
set< Point, PointComp > background_list
set of background points
vector< Tuple > point_list
set of current points
double MIN_DISTANCE
Minimum distance for valid point match.
size_t num_frames
Current number of frames.
size_t MAX_NUM_FRAMES
Max number of possible frames.
Detailed Description
Class used to track and monitor the keypoints.
Definition at line 64 of file PointTracker.h.
Constructor & Destructor Documentation
PointTracker::PointTracker ()
default constructor
Default constructor for the point tracking structure
Definition at line 40 of file PointTracker.cpp.
References MAX_NUM_FRAMES, MIN_DISTANCE, and num_frames.
{
    MIN_DISTANCE = 2.5;
    num_frames = 0;
    MAX_NUM_FRAMES = 50;
}
Member Function Documentation
int PointTracker::point_match (Point2f const & pt)
Point Match.
Check if a match exists between a point and the point list. Return the match index if found.
Parameters:
pt point to verify
Returns:
index of match, -1 if no match found.
Definition at line 98 of file PointTracker.cpp.
References MIN_DISTANCE, point_list, and PointDistanceL2().
Referenced by update_points().
{
    double dist;
    for(size_t i=0; i<point_list.size(); i++){
        dist = PointDistanceL2( pt, point_list[i].centroid);
        if(dist < MIN_DISTANCE)
            return i;
    }
    return -1;
}
void PointTracker::set_point_max_life (const int max_life) [inline]
Definition at line 75 of file PointTracker.h.
Referenced by init().
{
        MAX_NUM_FRAMES = max_life;
    }
vector< Tuple > PointTracker::update_points (vector< KeyPoint >const & list)
update the point positions
Update the points, adding new points and removing redundant ones.
Parameters:
list of keypoints
Returns:
revised list of point data structs
Definition at line 52 of file PointTracker.cpp.
References MAX_NUM_FRAMES, num_frames, point_list, and point_match().
Referenced by main().
{
    int idx;
    //take the input list and check for collisions
    for( size_t i=0; i<list.size(); i++){
        //check to see if a point matches
        idx = point_match(list[i].pt);
        if( idx >= 0 ){
            point_list[idx].found = true;
            point_list[idx].centroid.x = ((num_frames)/(double)(num_frames+1))*point_list[idx].centroid.x + (1/(double)(num_frames+1))*list[i].pt.x;
            point_list[idx].centroid.y = ((num_frames)/(double)(num_frames+1))*point_list[idx].centroid.y + (1/(double)(num_frames+1))*list[i].pt.y;
            continue;
        }
        //otherwise, add it to the list
        else{
            point_list.push_back(Tuple(list[i].pt));
        }
    }
    //iterate through point list, updating the strength of each point
    for( int i=0; i<(int)point_list.size(); i++){
        point_list[i].strength = (point_list[i].span*point_list[i].strength + point_list[i].found)/(double)(point_list[i].span+1);
        point_list[i].found = 0;
        point_list[i].span = min( point_list[i].span+1, MAX_NUM_FRAMES);
        if( point_list[i].strength < 0.3 )
            point_list.erase( point_list.begin() + i--);
    }
    num_frames++;
    if(num_frames > MAX_NUM_FRAMES)
        num_frames = MAX_NUM_FRAMES;
    return point_list;
}
Member Data Documentation
set<Point, PointComp> PointTracker::background_list [private]
set of background points
Definition at line 82 of file PointTracker.h.
size_t PointTracker::MAX_NUM_FRAMES [private]
Max number of possible frames.
Definition at line 94 of file PointTracker.h.
Referenced by PointTracker(), and update_points().
double PointTracker::MIN_DISTANCE [private]
Minimum distance for valid point match.
Definition at line 88 of file PointTracker.h.
Referenced by point_match(), and PointTracker().
size_t PointTracker::num_frames [private]
Current number of frames.
Definition at line 91 of file PointTracker.h.
Referenced by PointTracker(), and update_points().
vector<Tuple> PointTracker::point_list [private]
set of current points
Definition at line 85 of file PointTracker.h.
Referenced by point_match(), and update_points().
The documentation for this class was generated from the following files:
src/core/PointTracker.h
src/core/PointTracker.cpp